# -*- coding: utf-8 -*-
"""Sociology_Data_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wVNTGvOkZgqdUOL_uupRq4ZCi2BfK2lC
"""

pip install matplotlib==3.4.2

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from wordcloud import WordCloud, STOPWORDS
# %matplotlib inline

df = pd.read_csv(r"/content/Sociology_doc.csv")
df.head()

def word_cloud(feature=None):
  comment_words = ''
  stopwords = set(STOPWORDS)
  for val in feature:
    val = str(val)
    tokens = val.split()
    for i in range(len(tokens)):
        tokens[i] = tokens[i].lower()
    comment_words += " ".join(tokens)+" "
  wordcloud = WordCloud(width = 800, height = 800,background_color ='black',stopwords = stopwords,min_font_size = 10).generate(comment_words)                   
  plt.figure(figsize = (8, 8), facecolor = None)
  plt.imshow(wordcloud)
  plt.axis("off")
  plt.tight_layout(pad = 0)
  plt.show()

word_cloud(df[df['Gender']=='Male']['Were you at your hometown during covid times?'])

word_cloud(df[df['Gender']=='Female']['Were you at your hometown during covid times?'])

word_cloud(df[df['Gender']=='Male']['Were you provided with appropriate resources?'])

word_cloud(df[df['Gender']=='Female']['Were you provided with appropriate resources?'])

word_cloud(df[df['Gender']=='Male']['Do/Did you have to travel far from your home to access internet services or other resources required for online education?'])

word_cloud(df[df['Gender']=='Female']['Do/Did you have to travel far from your home to access internet services or other resources required for online education?'])

word_cloud(df[df['Gender']=='Male']['Do you have any siblings? Equality in terms of education'])

word_cloud(df[df['Gender']=='Female']['Do you have any siblings? Equality in terms of education'])

word_cloud(df[df['Gender']=='Male']['Did Household work affect your studies? How?'])

word_cloud(df[df['Gender']=='Female']['Did Household work affect your studies? How?'])

word_cloud(df[df['Gender']=='Male']['Comparison in between your studies before and after covid'])

word_cloud(df[df['Gender']=='Female']['Comparison in between your studies before and after covid'])

data_csv = pd.read_csv('/content/Digital Divide Survey (Responses) - Form Responses 1.csv')
data_csv = data_csv.fillna(value='No_Fill')
data_csv

data_csv[data_csv['Level of education']=='Undergraduate']['Place of Hometown'].value_counts()

data_csv[data_csv['Level of education']=='Undergraduate']['Place of Hometown'].value_counts().index.to_list()

"""# Feature-Wise Quantity Analysis"""

def single_feature(feature=None,x_label=None,y_label=None,title_bar=None,title_pie=None):
  wp = { 'linewidth' : 0.5, 'edgecolor' : "black" }
  plt.figure(figsize=(20,10))
  plt.subplot(121)
  ax = sns.countplot(x=feature)
  ax.set(xlabel=x_label, ylabel = y_label)
  ax.set_title(title_bar)
  t1 = feature.count()
  for c in ax.containers:
    labels = [f'{v.get_height()/t1*100:0.1f}%' for v in c]
    ax.bar_label(c, labels=labels, label_type='edge')
  plt.subplot(122)
  plt.pie(feature.value_counts().to_list(),labels=feature.value_counts().index.to_list(),autopct='%.2f%%',shadow=True,wedgeprops=wp)
  plt.title(title_pie)
  plt.legend()
  plt.show()
  plt.savefig('Graph_1.jpg')

single_feature(data_csv['Level of education'])

single_feature(data_csv['Place of Hometown'])

single_feature(data_csv['Do/Did you have to travel far for your home to access internet services or other resources required for online education?'])

single_feature(data_csv['Do you think your batch-mates performed better than you in online instruction mode because they had better resources (internet/infrastructure) at home?'])

single_feature(data_csv['Did you struggle with learning to operate various software in online mode of education?'])

single_feature(data_csv['How much would you rate your technology literacy?'])

"""# Inter-Features Analysis

## Analysis with respect to Level of Education
"""

plt.figure(figsize=(25,10))
plt.subplot(121)
ax = sns.countplot(x=data_csv['Level of education'],hue=data_csv['Place of Hometown'])
plt.subplot(122)
ax = sns.countplot(x=data_csv['Place of Hometown'],hue=data_csv['Level of education'])
plt.show()

plt.figure(figsize=(25,10))
plt.subplot(121)
ax = sns.countplot(x=data_csv['Level of education'],hue=data_csv['Did you struggle with learning to operate various software in online mode of education?'])
plt.subplot(122)
ax = sns.countplot(hue=data_csv['Level of education'],x=data_csv['Did you struggle with learning to operate various software in online mode of education?'])
plt.show()

plt.figure(figsize=(25,10))
plt.subplot(121)
ax = sns.countplot(x=data_csv['Level of education'],hue=data_csv['How much would you rate your technology literacy?'])
plt.subplot(122)
ax = sns.countplot(hue=data_csv['Level of education'],x=data_csv['How much would you rate your technology literacy?'])
plt.show()

"""## Analysis with respect to Place of Hometown"""

plt.figure(figsize=(25,10))
plt.subplot(121)
ax = sns.countplot(x=data_csv['Do/Did you have to travel far for your home to access internet services or other resources required for online education?'],hue=data_csv['Place of Hometown'])
plt.subplot(122)
ax = sns.countplot(hue=data_csv['Do/Did you have to travel far for your home to access internet services or other resources required for online education?'],x=data_csv['Place of Hometown'])
plt.show()

plt.figure(figsize=(25,10))
plt.subplot(121)
ax = sns.countplot(x=data_csv['Do you think your batch-mates performed better than you in online instruction mode because they had better resources (internet/infrastructure) at home?'],hue=data_csv['Place of Hometown'])
plt.subplot(122)
ax = sns.countplot(hue=data_csv['Do you think your batch-mates performed better than you in online instruction mode because they had better resources (internet/infrastructure) at home?'],x=data_csv['Place of Hometown'])
plt.show()

plt.figure(figsize=(25,10))
plt.subplot(121)
ax = sns.countplot(x=data_csv['Did you struggle with learning to operate various software in online mode of education?'],hue=data_csv['Place of Hometown'])
plt.subplot(122)
ax = sns.countplot(x=data_csv['Place of Hometown'],hue=data_csv['Did you struggle with learning to operate various software in online mode of education?'])
plt.show()

plt.figure(figsize=(25,10))
plt.subplot(121)
ax = sns.countplot(x=data_csv['How much would you rate your technology literacy?'],hue=data_csv['Place of Hometown'])
plt.subplot(122)
ax = sns.countplot(x=data_csv['Place of Hometown'],hue=data_csv['How much would you rate your technology literacy?'])
plt.show()

"""# Individual Location-wise graphs

## Literacy Score
"""

single_feature(data_csv[data_csv['Place of Hometown']=="Village"]["How much would you rate your technology literacy?"],'Technology Literacy Score (out of 10)','People Count','Literacy Score v/s Count Histogram','Literacy Score v/s Count Pie Chart')

single_feature(data_csv[data_csv['Place of Hometown']=="Metropolitan City"]["How much would you rate your technology literacy?"],'Technology Literacy Score (out of 10)','People Count','Literacy Score v/s Count Histogram','Literacy Score v/s Count Pie Chart')

single_feature(data_csv[data_csv['Place of Hometown']=="Sub-Urban Area"]["How much would you rate your technology literacy?"],'Technology Literacy Score (out of 10)','People Count','Literacy Score v/s Count Histogram','Literacy Score v/s Count Pie Chart')

"""## Struggle"""

single_feature(data_csv[data_csv['Place of Hometown']=="Village"]["Did you struggle with learning to operate various software in online mode of education?"],"Did you struggle with learning to operate various software in online mode of education?",'People Count','Struggle with Learning v/s Count Histogram','Struggle with Learning v/s Count Pie Chart')

single_feature(data_csv[data_csv['Place of Hometown']=="Sub-Urban Area"]["Did you struggle with learning to operate various software in online mode of education?"],"Did you struggle with learning to operate various software in online mode of education?",'People Count','Struggle with Learning v/s Count Histogram','Struggle with Learning v/s Count Pie Chart')

single_feature(data_csv[data_csv['Place of Hometown']=="Metropolitan City"]["Did you struggle with learning to operate various software in online mode of education?"],"Did you struggle with learning to operate various software in online mode of education?",'People Count','Struggle with Learning v/s Count Histogram','Struggle with Learning v/s Count Pie Chart')

"""## Batchmates"""

single_feature(data_csv[data_csv['Place of Hometown']=="Village"]["Do you think your batch-mates performed better than you in online instruction mode because they had better resources (internet/infrastructure) at home?"],"Do you think your batch-mates performed better than you in online instruction mode because they had better resources (internet/infrastructure) at home?",'People Count','Better Resources-Better Performance v/s Count Histogram','Better Resources-Better Performance v/s Count Pie Chart')

single_feature(data_csv[data_csv['Place of Hometown']=="Sub-Urban Area"]["Do you think your batch-mates performed better than you in online instruction mode because they had better resources (internet/infrastructure) at home?"],"Do you think your batch-mates performed better than you in online instruction mode because they had better resources (internet/infrastructure) at home?",'People Count','Better Resources-Better Performance v/s Count Histogram','Better Resources-Better Performance v/s Count Pie Chart')

single_feature(data_csv[data_csv['Place of Hometown']=="Metropolitan City"]["Do you think your batch-mates performed better than you in online instruction mode because they had better resources (internet/infrastructure) at home?"],"Do you think your batch-mates performed better than you in online instruction mode because they had better resources (internet/infrastructure) at home?",'People Count','Better Resources-Better Performance v/s Count Histogram','Better Resources-Better Performance v/s Count Pie Chart')

"""## Travel"""

single_feature(data_csv[data_csv['Place of Hometown']=="Village"]["Do/Did you have to travel far for your home to access internet services or other resources required for online education?"],"Do/Did you have to travel far for your home to access internet services or other resources required for online education?",'People Count','Resources Requirement v/s Count Histogram','Resources Requirement v/s Count Pie Chart')

single_feature(data_csv[data_csv['Place of Hometown']=="Sub-Urban Area"]["Do/Did you have to travel far for your home to access internet services or other resources required for online education?"],"Do/Did you have to travel far for your home to access internet services or other resources required for online education?",'People Count','Resources Requirement v/s Count Histogram','Resources Requirement v/s Count Pie Chart')

single_feature(data_csv[data_csv['Place of Hometown']=="Metropolitan City"]["Do/Did you have to travel far for your home to access internet services or other resources required for online education?"],"Do/Did you have to travel far for your home to access internet services or other resources required for online education?",'People Count','Resources Requirement v/s Count Histogram','Resources Requirement v/s Count Pie Chart')